spring.application.name=art-lover

spring.mongodb.uri=mongodb+srv://artuser:Voloshin%3D00@art-lover-cluster.92paorl.mongodb.net/artcollection

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

r2.bucket=
r2.account-id=
r2.access-key=
r2.secret-key=
r2.endpoint=

ai.apiKey=
google.search.engine.id=
europeana.api.key=
europeana.base-url=
smithsonian.api.key=