package com.example.art_lover.model;

// to connect to MongoDB Atlas -- need autogenerated id and document
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "artists")
public class ArtistModel {

    @Id
    private String id;

    private String name;

    public ArtistModel() {
        // required for frameworks
    }

    public ArtistModel(String id, String name) {
        this.id = id;
        this.name = name;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }
}