package com.example.art_lover.model;

// to connect to MongoDB Atlas -- need autogenerated id and document
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "artworks")
public class ArtworkModel {

    @Id
    private String id;

    private String title;
    private String artist;
    private String year;
    private String continent;
    private String country;
    private String description;
    private String movement;
    private Boolean bookmark;

    private String imageUrl;
    private String imageKey;

    private String userId;

    public ArtworkModel() {
        // required for frameworks
    }

    public ArtworkModel(String id, String title, String artist, String year, String continent, String country,
            Boolean bookmark, String imageUrl, String imageKey, String description, String movement, String userId) {
        this.id = id;
        this.title = title;
        this.artist = artist;
        this.year = year;
        this.continent = continent;
        this.country = country;
        this.bookmark = bookmark;
        this.imageUrl = imageUrl;
        this.imageKey = imageKey;
        this.description = description;
        this.movement = movement;
        this.userId = userId;
    }

    public String getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getArtist() {
        return artist;
    }

    public String getYear() {
        return year;
    }

    public String getContinent() {
        return continent;
    }

    public String getCountry() {
        return country;
    }

    public Boolean getBookmark() {
        return bookmark;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public String getImageKey() {
        return imageKey;
    }

    public String getDescription() {
        return description;
    }

    public String getMovement() {
        return movement;
    }

    public String getUserId() {
        return userId;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public void setBookmark(boolean bookmark) {
        this.bookmark = bookmark;
    }

    public void setContinent(String continent) {
        this.continent = continent;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public void setImageKey(String imageKey) {
        this.imageKey = imageKey;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setMovement(String movement) {
        this.movement = movement;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

}
